"""empty message

Revision ID: 12855fd3c8f9
Revises: 7ac57ba9e6a9
Create Date: 2020-09-28 17:28:49.921482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12855fd3c8f9'
down_revision = '7ac57ba9e6a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('title_blog', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_blogs_title_blog'), 'blogs', ['title_blog'], unique=False)
    op.drop_index('ix_blogs_blog_title', table_name='blogs')
    op.drop_column('blogs', 'blog_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_blogs_blog_title', 'blogs', ['blog_title'], unique=False)
    op.drop_index(op.f('ix_blogs_title_blog'), table_name='blogs')
    op.drop_column('blogs', 'title_blog')
    # ### end Alembic commands ###
