"""empty message

Revision ID: 212865a201b3
Revises: 12855fd3c8f9
Create Date: 2020-09-29 00:28:34.325959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212865a201b3'
down_revision = '12855fd3c8f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
