"""empty message

Revision ID: 352e446c0e85
Revises: efc0044193d3
Create Date: 2020-09-27 22:15:42.133381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '352e446c0e85'
down_revision = 'efc0044193d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_joined', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_joined')
    # ### end Alembic commands ###
