"""empty message

Revision ID: 459e6162f19c
Revises: 9481ee58f51b
Create Date: 2020-09-28 12:34:39.626880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459e6162f19c'
down_revision = '9481ee58f51b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('comment', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
