"""empty message

Revision ID: 7ac57ba9e6a9
Revises: 459e6162f19c
Create Date: 2020-09-28 13:06:59.758804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac57ba9e6a9'
down_revision = '459e6162f19c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('blogs', sa.Column('blog_title', sa.String(length=255), nullable=True))
    op.add_column('blogs', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('blogs', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('blogs', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_blogs_blog_title'), 'blogs', ['blog_title'], unique=False)
    op.create_index(op.f('ix_blogs_description'), 'blogs', ['description'], unique=False)
    op.create_foreign_key(None, 'blogs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.drop_index(op.f('ix_blogs_description'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_blog_title'), table_name='blogs')
    op.drop_column('blogs', 'user_id')
    op.drop_column('blogs', 'description')
    op.drop_column('blogs', 'date')
    op.drop_column('blogs', 'blog_title')
    op.drop_table('comments')
    # ### end Alembic commands ###
